version: '3.8'

services:
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: yarn start:debug
    ports:
      - ${DOCKER_APP_PORT}:3000
      - 9229:9229
      - 5555:5555
    user: 1000:1000
    networks:
      - nesjs-network
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - db
  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: yarn start:migrate:prod
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    restart: unless-stopped
    depends_on:
      - db
  db:
    container_name: nestjs-db
    image: mariadb
    restart: unless-stopped
    tty: true
    volumes:
      - ./.mariadb:/var/lib/mysql
    ports:
      - ${DOCKER_DB_PORT}:3306
    environment:
      MYSQL_DATABASE: nestjs_app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - nesjs-network

networks:
  nesjs-network:
